/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "stm32fxxxrcc.h"
#include "armsystick.h"
#include "stm32fxxxrtc.h"
#include "stm32fxxxusart1.h"
#include "stm32fxxxadc1.h"
#include "st7789.h"
/******/
#include "armfunction.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

int main(void)
{
    /* Loop forever */
	for(;;);
}
